apiVersion: v1
kind: Service
metadata:
  name: placeholder-service
  namespace: placeholder-namespace
spec:
  selector:
    app: placeholder-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
