#!/usr/bin/env python3
"""
Daedalus Phase I Local Runner

Purpose:
    Combine the Daedalus system prompt, a workflow request, and the engineering
    package output contract into a single Markdown engineering package scaffold.

This script does not call an LLM and does not execute infrastructure changes.
It prepares a reviewable prompt package that can be pasted into a local LLM,
Open WebUI, Ollama workflow, or future Daedalus execution layer.

Usage:
    python scripts/run_engineering_package.py

Optional:
    python scripts/run_engineering_package.py --workflow prompts/workflows/vaultwarden-engineering-request.md
    python scripts/run_engineering_package.py --output examples/vaultwarden-engineering-package.md
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
import sys


DEFAULT_SYSTEM_PROMPT = Path("prompts/system/daedalus-system-prompt.md")
DEFAULT_WORKFLOW = Path("prompts/workflows/vaultwarden-engineering-request.md")
DEFAULT_OUTPUT_CONTRACT = Path("prompts/output-contracts/engineering-package-v1.md")
DEFAULT_OUTPUT = Path("examples/vaultwarden-engineering-package.md")


ENGINEERING_PACKAGE_HEADER = """# Daedalus Engineering Package Scaffold

> Generated by the Daedalus Phase I local runner.
>
> This file is a planning artifact only. It does not execute changes, modify infrastructure, create secrets, or approve deployment.
"""


def read_markdown(path: Path) -> str:
    """Read a Markdown file and return stripped content."""
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    if not path.is_file():
        raise IsADirectoryError(f"Expected a file, got directory: {path}")
    return path.read_text(encoding="utf-8").strip()


def build_package(system_prompt: str, workflow: str, output_contract: str) -> str:
    """Build the combined Daedalus engineering package scaffold."""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    return f"""{ENGINEERING_PACKAGE_HEADER}

## Metadata

- Generated At: {generated_at}
- Mode: Phase I / Engineering Brain
- Execution Authority: Disabled
- Human Approval Required: Yes

## Operator Safety Boundary

Daedalus may plan, document, analyze, and generate reviewable skeletons.
Daedalus must not execute infrastructure changes, approve its own work, create production secrets, or claim deployment completion.

---

## 1. Daedalus System Prompt

```markdown
{system_prompt}
```

---

## 2. Workflow Request

```markdown
{workflow}
```

---

## 3. Output Contract

```markdown
{output_contract}
```

---

## 4. Combined Prompt for Local LLM

Copy the section below into Open WebUI, Ollama, or another local LLM interface.

```text
You are operating as Daedalus, an Infrastructure Security Engineer.

Follow the system prompt, workflow request, and output contract exactly.
Do not execute changes.
Do not claim deployment completion.
Do not generate production credentials.
Keep the human engineer in the approval loop.

SYSTEM PROMPT:
{system_prompt}

WORKFLOW REQUEST:
{workflow}

OUTPUT CONTRACT:
{output_contract}

TASK:
Generate the complete engineering package for the workflow request using the required output contract.
```

---

## 5. Human Review Notes

Use this area to record findings after testing the prompt against a local LLM.

### Review Checklist

- [ ] Output follows the engineering package contract
- [ ] Architecture is specific and actionable
- [ ] Security concerns are identified
- [ ] Validation steps are included
- [ ] Rollback steps are included
- [ ] Human approval gates are explicit
- [ ] No secrets are generated
- [ ] No deployment is claimed
- [ ] Output can be committed to Git
- [ ] Output can be converted into ClickUp tasks

### Engineer Notes

```text
Add review notes here after testing.
```
""".rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Daedalus Phase I engineering package scaffold."
    )
    parser.add_argument(
        "--system-prompt",
        type=Path,
        default=DEFAULT_SYSTEM_PROMPT,
        help=f"Path to Daedalus system prompt. Default: {DEFAULT_SYSTEM_PROMPT}",
    )
    parser.add_argument(
        "--workflow",
        type=Path,
        default=DEFAULT_WORKFLOW,
        help=f"Path to workflow request. Default: {DEFAULT_WORKFLOW}",
    )
    parser.add_argument(
        "--output-contract",
        type=Path,
        default=DEFAULT_OUTPUT_CONTRACT,
        help=f"Path to output contract. Default: {DEFAULT_OUTPUT_CONTRACT}",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output Markdown file. Default: {DEFAULT_OUTPUT}",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        system_prompt = read_markdown(args.system_prompt)
        workflow = read_markdown(args.workflow)
        output_contract = read_markdown(args.output_contract)
        package = build_package(system_prompt, workflow, output_contract)

        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(package, encoding="utf-8")

    except Exception as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    print(f"[OK] Engineering package scaffold written to: {args.output}")
    print("[OK] Review the generated Markdown before using it with a local LLM.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
